#! /bin/zsh

wget 'https://storage.googleapis.com/public-download-files/hgnc/tsv/tsv/hgnc_complete_set.txt'
wget 'https://www.informatics.jax.org/downloads/reports/HGNC_AllianceHomology.rpt'
wget 'https://zfin.org/downloads/human_orthos.txt'
